services:
  - type: web
    name: teamup-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://teamup-frontend.vercel.app
      - key: MONGODB_URI
        sync: false # This will be manually set in Render dashboard 